#开发配置
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qishengghuo
    username: root
    password: root
server:
  port: 8011


mybatis:
   configuration:
      map-underscore-to-camelCase: true
      mapper-locations: "classpath*:mapper*/**/*.xml"