#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qishengghuo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8011


mybatis:
   configuration:
      map-underscore-to-camelCase: true
      mapper-locations: "classpath:mapper/*.xml"